#ifndef H_HLSL_COMPUTE_CONSTANTS
#define H_HLSL_COMPUTE_CONSTANTS

#include "Constants.h"

#define BACK_BUFFER_RESOLUTION uint2(WINDOW_WIDTH, WINDOW_HEIGHT)
#define GROUP_COUNT uint2(COMPUTE_GROUP_COUNT_X, COMPUTE_GROUP_COUNT_Y)

#define NUM_THREADS uint2(BACK_BUFFER_RESOLUTION / GROUP_COUNT)

#endif